Nov 10 14:17:41.900439 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:17:41.900391    2296 pod_workers.go:1300] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"controller\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=controller pod=cloud-network-config-controller-74ffd6bb6d-7979c_openshift-cloud-network-config-controller(74b53336-ddca-47c4-a281-49118930aa12)\"" pod="openshift-cloud-network-config-controller/cloud-network-config-controller-74ffd6bb6d-7979c" podUID=74b53336-ddca-47c4-a281-49118930aa12
Nov 10 14:17:44.067049 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: I1110 14:17:44.066997    2296 patch_prober.go:28] interesting pod/etcd-guard-ci-ln-b3f5vqb-72292-v2kk6-master-0 container/guard namespace/openshift-etcd: Readiness probe status=failure output="Get \"https://10.0.0.5:9980/readyz\": dial tcp 10.0.0.5:9980: connect: connection refused" start-of-body=
Nov 10 14:17:44.067767 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: I1110 14:17:44.067083    2296 prober.go:107] "Probe failed" probeType="Readiness" pod="openshift-etcd/etcd-guard-ci-ln-b3f5vqb-72292-v2kk6-master-0" podUID=8cd216f8-1c68-40d4-94b4-a8b66e09a898 containerName="guard" probeResult=failure output="Get \"https://10.0.0.5:9980/readyz\": dial tcp 10.0.0.5:9980: connect: connection refused"
Nov 10 14:17:47.146551 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:17:47.146524    2296 remote_runtime.go:415] "ContainerStatus from runtime service failed" err="rpc error: code = NotFound desc = could not find container \"fd7e62fd41ffd4e5f2952b4dec03e748883ab0e880da9b215ba79adb9bd04441\": container with ID starting with fd7e62fd41ffd4e5f2952b4dec03e748883ab0e880da9b215ba79adb9bd04441 not found: ID does not exist" containerID="fd7e62fd41ffd4e5f2952b4dec03e748883ab0e880da9b215ba79adb9bd04441"
Nov 10 14:17:47.147050 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:17:47.147030    2296 remote_runtime.go:415] "ContainerStatus from runtime service failed" err="rpc error: code = NotFound desc = could not find container \"61a07dd5dec02351d20d92dcbc40b0a2e5b3946a851a12db2c34fb392a87b481\": container with ID starting with 61a07dd5dec02351d20d92dcbc40b0a2e5b3946a851a12db2c34fb392a87b481 not found: ID does not exist" containerID="61a07dd5dec02351d20d92dcbc40b0a2e5b3946a851a12db2c34fb392a87b481"
Nov 10 14:17:47.147594 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:17:47.147425    2296 remote_runtime.go:415] "ContainerStatus from runtime service failed" err="rpc error: code = NotFound desc = could not find container \"c08991f9262c75a7bfaabbb4ce4a950e30f16afeb519ebbee61e0ef11ce0cd3b\": container with ID starting with c08991f9262c75a7bfaabbb4ce4a950e30f16afeb519ebbee61e0ef11ce0cd3b not found: ID does not exist" containerID="c08991f9262c75a7bfaabbb4ce4a950e30f16afeb519ebbee61e0ef11ce0cd3b"
Nov 10 14:17:47.147982 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:17:47.147938    2296 remote_runtime.go:415] "ContainerStatus from runtime service failed" err="rpc error: code = NotFound desc = could not find container \"aa5826c2d59118135bd56b2bf66115fbefb0d7402eb1a4357cbd587d3364906f\": container with ID starting with aa5826c2d59118135bd56b2bf66115fbefb0d7402eb1a4357cbd587d3364906f not found: ID does not exist" containerID="aa5826c2d59118135bd56b2bf66115fbefb0d7402eb1a4357cbd587d3364906f"
Nov 10 14:17:47.148402 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:17:47.148359    2296 remote_runtime.go:415] "ContainerStatus from runtime service failed" err="rpc error: code = NotFound desc = could not find container \"1e76ef5ae2ad60b8ef87be15307b142cc4456efe10ddccf88d604142c02d6a8b\": container with ID starting with 1e76ef5ae2ad60b8ef87be15307b142cc4456efe10ddccf88d604142c02d6a8b not found: ID does not exist" containerID="1e76ef5ae2ad60b8ef87be15307b142cc4456efe10ddccf88d604142c02d6a8b"
Nov 10 14:17:47.148746 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:17:47.148721    2296 remote_runtime.go:415] "ContainerStatus from runtime service failed" err="rpc error: code = NotFound desc = could not find container \"ebab3c1da42e67c4b38274567340fea103f04bce934ec5eb78bfc2779bfd0236\": container with ID starting with ebab3c1da42e67c4b38274567340fea103f04bce934ec5eb78bfc2779bfd0236 not found: ID does not exist" containerID="ebab3c1da42e67c4b38274567340fea103f04bce934ec5eb78bfc2779bfd0236"
Nov 10 14:17:47.149218 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:17:47.149198    2296 remote_runtime.go:415] "ContainerStatus from runtime service failed" err="rpc error: code = NotFound desc = could not find container \"c6ac138165ab199e2146c760a17123cc41bddf58b0b6a3ae075cc5ea7b78dfa9\": container with ID starting with c6ac138165ab199e2146c760a17123cc41bddf58b0b6a3ae075cc5ea7b78dfa9 not found: ID does not exist" containerID="c6ac138165ab199e2146c760a17123cc41bddf58b0b6a3ae075cc5ea7b78dfa9"
Nov 10 14:17:49.066288 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: I1110 14:17:49.066238    2296 patch_prober.go:28] interesting pod/etcd-guard-ci-ln-b3f5vqb-72292-v2kk6-master-0 container/guard namespace/openshift-etcd: Readiness probe status=failure output="Get \"https://10.0.0.5:9980/readyz\": dial tcp 10.0.0.5:9980: connect: connection refused" start-of-body=
Nov 10 14:17:49.067049 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: I1110 14:17:49.066316    2296 prober.go:107] "Probe failed" probeType="Readiness" pod="openshift-etcd/etcd-guard-ci-ln-b3f5vqb-72292-v2kk6-master-0" podUID=8cd216f8-1c68-40d4-94b4-a8b66e09a898 containerName="guard" probeResult=failure output="Get \"https://10.0.0.5:9980/readyz\": dial tcp 10.0.0.5:9980: connect: connection refused"
Nov 10 14:17:54.066789 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: I1110 14:17:54.066741    2296 patch_prober.go:28] interesting pod/etcd-guard-ci-ln-b3f5vqb-72292-v2kk6-master-0 container/guard namespace/openshift-etcd: Readiness probe status=failure output="Get \"https://10.0.0.5:9980/readyz\": dial tcp 10.0.0.5:9980: connect: connection refused" start-of-body=
Nov 10 14:17:54.067295 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: I1110 14:17:54.066826    2296 prober.go:107] "Probe failed" probeType="Readiness" pod="openshift-etcd/etcd-guard-ci-ln-b3f5vqb-72292-v2kk6-master-0" podUID=8cd216f8-1c68-40d4-94b4-a8b66e09a898 containerName="guard" probeResult=failure output="Get \"https://10.0.0.5:9980/readyz\": dial tcp 10.0.0.5:9980: connect: connection refused"
Nov 10 14:17:56.901035 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:17:56.900982    2296 pod_workers.go:1300] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"controller\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=controller pod=cloud-network-config-controller-74ffd6bb6d-7979c_openshift-cloud-network-config-controller(74b53336-ddca-47c4-a281-49118930aa12)\"" pod="openshift-cloud-network-config-controller/cloud-network-config-controller-74ffd6bb6d-7979c" podUID=74b53336-ddca-47c4-a281-49118930aa12
Nov 10 14:17:59.066255 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: I1110 14:17:59.066200    2296 patch_prober.go:28] interesting pod/etcd-guard-ci-ln-b3f5vqb-72292-v2kk6-master-0 container/guard namespace/openshift-etcd: Readiness probe status=failure output="Get \"https://10.0.0.5:9980/readyz\": dial tcp 10.0.0.5:9980: connect: connection refused" start-of-body=
Nov 10 14:17:59.066517 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: I1110 14:17:59.066285    2296 prober.go:107] "Probe failed" probeType="Readiness" pod="openshift-etcd/etcd-guard-ci-ln-b3f5vqb-72292-v2kk6-master-0" podUID=8cd216f8-1c68-40d4-94b4-a8b66e09a898 containerName="guard" probeResult=failure output="Get \"https://10.0.0.5:9980/readyz\": dial tcp 10.0.0.5:9980: connect: connection refused"
Nov 10 14:18:09.902164 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:18:09.902141    2296 pod_workers.go:1300] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"controller\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=controller pod=cloud-network-config-controller-74ffd6bb6d-7979c_openshift-cloud-network-config-controller(74b53336-ddca-47c4-a281-49118930aa12)\"" pod="openshift-cloud-network-config-controller/cloud-network-config-controller-74ffd6bb6d-7979c" podUID=74b53336-ddca-47c4-a281-49118930aa12
Nov 10 14:18:20.902344 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:18:20.901913    2296 pod_workers.go:1300] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"controller\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=controller pod=cloud-network-config-controller-74ffd6bb6d-7979c_openshift-cloud-network-config-controller(74b53336-ddca-47c4-a281-49118930aa12)\"" pod="openshift-cloud-network-config-controller/cloud-network-config-controller-74ffd6bb6d-7979c" podUID=74b53336-ddca-47c4-a281-49118930aa12
Nov 10 14:18:33.901636 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:18:33.901079    2296 pod_workers.go:1300] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"controller\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=controller pod=cloud-network-config-controller-74ffd6bb6d-7979c_openshift-cloud-network-config-controller(74b53336-ddca-47c4-a281-49118930aa12)\"" pod="openshift-cloud-network-config-controller/cloud-network-config-controller-74ffd6bb6d-7979c" podUID=74b53336-ddca-47c4-a281-49118930aa12
Nov 10 14:18:41.428252 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:18:41.427902    2296 cpu_manager.go:396] "RemoveStaleState: removing container" podUID="d8d476ba-41bc-4611-a997-d838c758f6bb" containerName="installer"
Nov 10 14:18:45.900346 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:18:45.900288    2296 pod_workers.go:1300] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"controller\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=controller pod=cloud-network-config-controller-74ffd6bb6d-7979c_openshift-cloud-network-config-controller(74b53336-ddca-47c4-a281-49118930aa12)\"" pod="openshift-cloud-network-config-controller/cloud-network-config-controller-74ffd6bb6d-7979c" podUID=74b53336-ddca-47c4-a281-49118930aa12
Nov 10 14:18:57.900518 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:18:57.900461    2296 pod_workers.go:1300] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"controller\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=controller pod=cloud-network-config-controller-74ffd6bb6d-7979c_openshift-cloud-network-config-controller(74b53336-ddca-47c4-a281-49118930aa12)\"" pod="openshift-cloud-network-config-controller/cloud-network-config-controller-74ffd6bb6d-7979c" podUID=74b53336-ddca-47c4-a281-49118930aa12
Nov 10 14:19:11.904392 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:19:11.904025    2296 pod_workers.go:1300] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"controller\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=controller pod=cloud-network-config-controller-74ffd6bb6d-7979c_openshift-cloud-network-config-controller(74b53336-ddca-47c4-a281-49118930aa12)\"" pod="openshift-cloud-network-config-controller/cloud-network-config-controller-74ffd6bb6d-7979c" podUID=74b53336-ddca-47c4-a281-49118930aa12
Nov 10 14:19:25.902044 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:19:25.902010    2296 pod_workers.go:1300] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"controller\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=controller pod=cloud-network-config-controller-74ffd6bb6d-7979c_openshift-cloud-network-config-controller(74b53336-ddca-47c4-a281-49118930aa12)\"" pod="openshift-cloud-network-config-controller/cloud-network-config-controller-74ffd6bb6d-7979c" podUID=74b53336-ddca-47c4-a281-49118930aa12
Nov 10 14:19:29.694961 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:19:29.693294    2296 remote_runtime.go:415] "ContainerStatus from runtime service failed" err="rpc error: code = NotFound desc = could not find container \"d29252b0255311b128200339e00d46990e99322696e7cf9f502999e8c7f06b9d\": container with ID starting with d29252b0255311b128200339e00d46990e99322696e7cf9f502999e8c7f06b9d not found: ID does not exist" containerID="d29252b0255311b128200339e00d46990e99322696e7cf9f502999e8c7f06b9d"
Nov 10 14:19:29.698683 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:19:29.697082    2296 remote_runtime.go:415] "ContainerStatus from runtime service failed" err="rpc error: code = NotFound desc = could not find container \"6ff3e4045b1ff480d5a03baacc53de0edbb8e00c18d816e4d6a01222852ea8c4\": container with ID starting with 6ff3e4045b1ff480d5a03baacc53de0edbb8e00c18d816e4d6a01222852ea8c4 not found: ID does not exist" containerID="6ff3e4045b1ff480d5a03baacc53de0edbb8e00c18d816e4d6a01222852ea8c4"
Nov 10 14:19:37.888553 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:19:37.888514    2296 cadvisor_stats_provider.go:442] "Partial failure issuing cadvisor.ContainerInfoV2" err="partial failures: [\"/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod8c4747a5_36f5_40ee_9376_949dfba44a97.slice\": RecentStats: unable to find data in memory cache]"
Nov 10 14:19:40.900369 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:19:40.900323    2296 pod_workers.go:1300] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"controller\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=controller pod=cloud-network-config-controller-74ffd6bb6d-7979c_openshift-cloud-network-config-controller(74b53336-ddca-47c4-a281-49118930aa12)\"" pod="openshift-cloud-network-config-controller/cloud-network-config-controller-74ffd6bb6d-7979c" podUID=74b53336-ddca-47c4-a281-49118930aa12
Nov 10 14:19:44.965671 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:19:44.965527    2296 cadvisor_stats_provider.go:442] "Partial failure issuing cadvisor.ContainerInfoV2" err="partial failures: [\"/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod8c4747a5_36f5_40ee_9376_949dfba44a97.slice\": RecentStats: unable to find data in memory cache]"
Nov 10 14:19:44.966350 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:19:44.965728    2296 cadvisor_stats_provider.go:442] "Partial failure issuing cadvisor.ContainerInfoV2" err="partial failures: [\"/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod8c4747a5_36f5_40ee_9376_949dfba44a97.slice\": RecentStats: unable to find data in memory cache]"
Nov 10 14:19:47.910909 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:19:47.910841    2296 cadvisor_stats_provider.go:442] "Partial failure issuing cadvisor.ContainerInfoV2" err="partial failures: [\"/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod8c4747a5_36f5_40ee_9376_949dfba44a97.slice\": RecentStats: unable to find data in memory cache]"
Nov 10 14:19:51.780563 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:19:51.780527    2296 cadvisor_stats_provider.go:442] "Partial failure issuing cadvisor.ContainerInfoV2" err="partial failures: [\"/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod8c4747a5_36f5_40ee_9376_949dfba44a97.slice\": RecentStats: unable to find data in memory cache]"
Nov 10 14:19:51.780563 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:19:51.780547    2296 cadvisor_stats_provider.go:442] "Partial failure issuing cadvisor.ContainerInfoV2" err="partial failures: [\"/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod8c4747a5_36f5_40ee_9376_949dfba44a97.slice\": RecentStats: unable to find data in memory cache]"
Nov 10 14:19:55.901403 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:19:55.901173    2296 pod_workers.go:1300] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"controller\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=controller pod=cloud-network-config-controller-74ffd6bb6d-7979c_openshift-cloud-network-config-controller(74b53336-ddca-47c4-a281-49118930aa12)\"" pod="openshift-cloud-network-config-controller/cloud-network-config-controller-74ffd6bb6d-7979c" podUID=74b53336-ddca-47c4-a281-49118930aa12
Nov 10 14:19:58.022368 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:19:58.022322    2296 cadvisor_stats_provider.go:442] "Partial failure issuing cadvisor.ContainerInfoV2" err="partial failures: [\"/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod8c4747a5_36f5_40ee_9376_949dfba44a97.slice\": RecentStats: unable to find data in memory cache]"
Nov 10 14:20:06.900280 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:20:06.899866    2296 pod_workers.go:1300] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"controller\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=controller pod=cloud-network-config-controller-74ffd6bb6d-7979c_openshift-cloud-network-config-controller(74b53336-ddca-47c4-a281-49118930aa12)\"" pod="openshift-cloud-network-config-controller/cloud-network-config-controller-74ffd6bb6d-7979c" podUID=74b53336-ddca-47c4-a281-49118930aa12
Nov 10 14:20:08.124884 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:20:08.124850    2296 cadvisor_stats_provider.go:442] "Partial failure issuing cadvisor.ContainerInfoV2" err="partial failures: [\"/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod8c4747a5_36f5_40ee_9376_949dfba44a97.slice\": RecentStats: unable to find data in memory cache]"
Nov 10 14:20:14.966047 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:20:14.965929    2296 cadvisor_stats_provider.go:442] "Partial failure issuing cadvisor.ContainerInfoV2" err="partial failures: [\"/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod8c4747a5_36f5_40ee_9376_949dfba44a97.slice\": RecentStats: unable to find data in memory cache]"
Nov 10 14:20:14.966850 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:20:14.966137    2296 cadvisor_stats_provider.go:442] "Partial failure issuing cadvisor.ContainerInfoV2" err="partial failures: [\"/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod8c4747a5_36f5_40ee_9376_949dfba44a97.slice\": RecentStats: unable to find data in memory cache]"
Nov 10 14:20:18.141364 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:20:18.141319    2296 cadvisor_stats_provider.go:442] "Partial failure issuing cadvisor.ContainerInfoV2" err="partial failures: [\"/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod8c4747a5_36f5_40ee_9376_949dfba44a97.slice\": RecentStats: unable to find data in memory cache]"
Nov 10 14:20:20.900585 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:20:20.900544    2296 pod_workers.go:1300] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"controller\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=controller pod=cloud-network-config-controller-74ffd6bb6d-7979c_openshift-cloud-network-config-controller(74b53336-ddca-47c4-a281-49118930aa12)\"" pod="openshift-cloud-network-config-controller/cloud-network-config-controller-74ffd6bb6d-7979c" podUID=74b53336-ddca-47c4-a281-49118930aa12
Nov 10 14:20:21.783925 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:20:21.783887    2296 cadvisor_stats_provider.go:442] "Partial failure issuing cadvisor.ContainerInfoV2" err="partial failures: [\"/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod8c4747a5_36f5_40ee_9376_949dfba44a97.slice\": RecentStats: unable to find data in memory cache]"
Nov 10 14:20:21.784358 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:20:21.783887    2296 cadvisor_stats_provider.go:442] "Partial failure issuing cadvisor.ContainerInfoV2" err="partial failures: [\"/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod8c4747a5_36f5_40ee_9376_949dfba44a97.slice\": RecentStats: unable to find data in memory cache]"
Nov 10 14:20:28.238809 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:20:28.238753    2296 cadvisor_stats_provider.go:442] "Partial failure issuing cadvisor.ContainerInfoV2" err="partial failures: [\"/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod8c4747a5_36f5_40ee_9376_949dfba44a97.slice\": RecentStats: unable to find data in memory cache]"
Nov 10 14:20:32.900422 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:20:32.900385    2296 pod_workers.go:1300] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"controller\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=controller pod=cloud-network-config-controller-74ffd6bb6d-7979c_openshift-cloud-network-config-controller(74b53336-ddca-47c4-a281-49118930aa12)\"" pod="openshift-cloud-network-config-controller/cloud-network-config-controller-74ffd6bb6d-7979c" podUID=74b53336-ddca-47c4-a281-49118930aa12
Nov 10 14:20:45.900544 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:20:45.900493    2296 pod_workers.go:1300] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"controller\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=controller pod=cloud-network-config-controller-74ffd6bb6d-7979c_openshift-cloud-network-config-controller(74b53336-ddca-47c4-a281-49118930aa12)\"" pod="openshift-cloud-network-config-controller/cloud-network-config-controller-74ffd6bb6d-7979c" podUID=74b53336-ddca-47c4-a281-49118930aa12
Nov 10 14:20:56.900332 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:20:56.900034    2296 pod_workers.go:1300] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"controller\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=controller pod=cloud-network-config-controller-74ffd6bb6d-7979c_openshift-cloud-network-config-controller(74b53336-ddca-47c4-a281-49118930aa12)\"" pod="openshift-cloud-network-config-controller/cloud-network-config-controller-74ffd6bb6d-7979c" podUID=74b53336-ddca-47c4-a281-49118930aa12
Nov 10 14:21:09.903370 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:21:09.903241    2296 pod_workers.go:1300] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"controller\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=controller pod=cloud-network-config-controller-74ffd6bb6d-7979c_openshift-cloud-network-config-controller(74b53336-ddca-47c4-a281-49118930aa12)\"" pod="openshift-cloud-network-config-controller/cloud-network-config-controller-74ffd6bb6d-7979c" podUID=74b53336-ddca-47c4-a281-49118930aa12
Nov 10 14:21:24.900734 ci-ln-b3f5vqb-72292-v2kk6-master-0 kubenswrapper[2296]: E1110 14:21:24.899996    2296 pod_workers.go:1300] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"controller\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=controller pod=cloud-network-config-controller-74ffd6bb6d-7979c_openshift-cloud-network-config-controller(74b53336-ddca-47c4-a281-49118930aa12)\"" pod="openshift-cloud-network-config-controller/cloud-network-config-controller-74ffd6bb6d-7979c" podUID=74b53336-ddca-47c4-a281-49118930aa12
